### ISSUE TITLE
/me endpoint causes server error in dev

### ISSUE THREAD

**Issue by vvihorev** [Kosjenka-Reading-App/Backend-API#16]
[crash log](https://github.com/Kosjenka-Reading-App/Backend-API/files/13397793/message.txt)

**Comment by vvihorev** [comment]
/me works for regular and admin accounts, return `account not found` for superadmin

**Comment by tim14996** [comment]
I guess we can close this, @Ambre16 fixed it right?

**Comment by Ambre16** [comment]
@DoStini Is it fixed ?

**Comment by vvihorev** [comment]
Tested for all account types, lgtm, closing! 😎
